export const listsIdeas = [
  {
    emoji: "✈️",
    name: "Prepare for a trip",
    items: [
      "Book flight or transportation",
      "Reserve accommodation",
      "Pack clothes for all weather",
      "Pack toiletries and essentials",
      "Print or save travel documents",
      "Prepare travel insurance",
      "Charge devices and pack chargers",
      "Notify bank of travel dates",
      "Check destination's COVID requirements",
      "Plan sightseeing and activities",
    ],
  },
  {
    emoji: "💻",
    name: "Set up your new computer",
    items: [
      "Unbox and connect peripherals",
      "Install necessary software",
      "Set up your email",
      "Install antivirus and security updates",
      "Customize desktop and settings",
      "Back up important files",
      "Create a system restore point",
      "Sync cloud storage",
      "Set up printer and devices",
      "Test system performance",
    ],
  },
  {
    emoji: "📚",
    name: "Plan study schedule",
    items: [
      "Review syllabus and subjects",
      "Set study goals",
      "Create a daily study timetable",
      "Allocate time for breaks",
      "Gather study materials",
      "Set up study space",
      "Plan for mock exams",
      "Prioritize difficult subjects",
      "Organize study group sessions",
      "Track your progress",
    ],
  },
  {
    emoji: "🍳",
    name: "Prepare a week's meals",
    items: [
      "Plan meals for the week",
      "Create a shopping list",
      "Buy groceries",
      "Prep vegetables and ingredients",
      "Cook and portion meals",
      "Store meals in containers",
      "Label meals with dates",
      "Clean cooking equipment",
      "Organize the fridge",
      "Set reminders for meal times",
    ],
  },
  {
    emoji: "🏃‍♂️",
    name: "Create a workout routine",
    items: [
      "Set fitness goals",
      "Choose workout types (cardio, strength)",
      "Create a weekly schedule",
      "Warm up before each session",
      "Start with lighter weights",
      "Include rest days",
      "Track your progress",
      "Hydrate and fuel your body",
      "Get the right workout gear",
      "Listen to your body",
    ],
  },
  {
    emoji: "🎉",
    name: "Organize a party or event",
    items: [
      "Choose a theme or occasion",
      "Set a date and time",
      "Create a guest list",
      "Send out invitations",
      "Plan food and drinks",
      "Decorate the venue",
      "Arrange music or entertainment",
      "Set up a photo area",
      "Prepare a schedule for the event",
      "Clean up after the event",
    ],
  },
  {
    emoji: "🛒",
    name: "Do weekly grocery shopping",
    items: [
      "Check pantry for items needed",
      "Make a meal plan for the week",
      "Create a shopping list",
      "Check for sales and discounts",
      "Organize shopping list by categories",
      "Grab reusable shopping bags",
      "Shop for fresh produce",
      "Buy snacks and beverages",
      "Pick up any household items",
      "Organize groceries when you get home",
    ],
  },
  {
    emoji: "🧹",
    name: "Clean & organize your room",
    items: [
      "Pick up any clutter",
      "Dust surfaces",
      "Vacuum or sweep the floor",
      "Wipe down windows and mirrors",
      "Organize clothes and shoes",
      "Make the bed",
      "Declutter desk or workspace",
      "Sort through papers and files",
      "Rearrange furniture if needed",
      "Take out the trash",
    ],
  },
  {
    emoji: "🎨",
    name: "Start a new creative hobby",
    items: [
      "Choose a hobby (painting, knitting, etc.)",
      "Gather necessary supplies",
      "Create a dedicated space for your hobby",
      "Set aside time to practice",
      "Take a class or watch tutorials",
      "Start with simple projects",
      "Experiment with different techniques",
      "Join online communities or forums",
      "Track your progress",
      "Share your creations with others",
    ],
  },
  {
    emoji: "📦",
    name: "Pack for a move",
    items: [
      "Sort through belongings",
      "Pack non-essential items first",
      "Label each box by room",
      "Wrap fragile items securely",
      "Pack clothing in suitcases",
      "Create an essentials box (toiletries, meds)",
      "Arrange for moving help",
      "Set up utilities at new place",
      "Clean the old house",
      "Check inventory before the move",
    ],
  },
];
